apiVersion: v1
kind: Service
metadata:
  name: landing-page
spec:
  type: LoadBalancer
  selector:
    app: landing-page
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: landing-page
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: landing-page
        tier: backend
    spec:
      containers:
        - name: landing-page
          image: gcr.io/wiresafe-project/wiresafe-landing-page
          ports:
          - name: http
            containerPort: 80
