kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: landing-page
  labels:
    app: landing-page
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
        - name: webserver
          image: gcr.io/wiresafe-project/wiresafe-landing-page
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: landing-page
spec:
  type: NodePort
  selector:
    app: landing-page
  ports:
  - port: 80
    targetPort: 80
