# wordpress service
kind: Service
apiVersion: v1
metadata:
  namespace: wordpress
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort
---
# expose the website
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: wordpress
  name: wordpress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: blog-wiresafe-com
spec:
  rules:
  - host: blog.wiresafe.com
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 80

